### ISSUE TITLE
"Adjust machine and pulley size" won't work in 7.1.1

### ISSUE THREAD

**Issue by pkmcnc** [MarginallyClever/Makelangelo#89]
Just throws a bunch of errors to command window.

"About" window looks weird http://i.imgur.com/rPgM6Oq.png

And I can't see recently used files list...? So pity if it's gone.

**Comment by virtuoushub** [comment]
The "About" window looking weird is due to the translation files included in the release zip not containing [these lines](https://github.com/MarginallyClever/Makelangelo/blob/master/java/languages/english.xml#L628-666). A workaround is to replace the ones included in the zip with the ones on [GitHub](https://github.com/MarginallyClever/Makelangelo/tree/master/java/languages).

I have not investigated what is going on with "Adjust machine and pulley size" yet.

**Comment by i-make-robots** [comment]
I'll get started on these on monday.  I need the weekend to deal with the
emotional BS of putting out a disappointing build.  Not sure what to do
about these bugs.

On Sat, May 9, 2015 at 7:19 AM, Peter Colapietro <notifications@github.com>
wrote:

> The "About" window looking weird is due to the translation files included
> in the release zip not containing these lines
> <https://github.com/MarginallyClever/Makelangelo/blob/master/java/languages/english.xml#L628-666>.
> A workaround is to replace the ones included in the zip with the ones on
> GitHub
> <https://github.com/MarginallyClever/Makelangelo/tree/master/java/languages>
> .
>
> I have not investigated what is going on with "Adjust machine and pulley
> size" yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/89#issuecomment-100495803>
> .
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by virtuoushub** [comment]
@i-make-robots I fixed the bugs in my branch. See the Pull Request I just opened: #91

The only thing needed before merging that into the master branch is testing that my fixes do indeed resolve the bugs, and then tagging/packaging the jar as version 7.1.2 instead of the currently packaged 7.1.2-SNAPSHOT.

I am available for assistance with packaging. Depending on your build server's speed; it takes less than a minute to complete with a couple more minutes for committing/tagging the update appropriately. I estimate between 10-15 minutes tops.
